branches:
  - main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - message: |-
        chore(release): ${nextRelease.version} [skip ci]
        
        ${nextRelease.notes}
      assets:
        - CHANGELOG.md
  - - '@semantic-release/exec'
    - publishCmd: |-
        docker buildx build . --push --tag ammmze/akri-ser2net-broker --tag ammmze/akri-ser2net-broker:${nextRelease.version} --platform linux/amd64,linux/arm/v7,linux/arm64
  # - - '@semantic-release-plus/docker'
  #   - name: ammmze/akri-ser2net-broker
  #     registryUrl: docker.io
  #     publishLatestTag: true
  #     publishMajorTag: true
  #     publishMinorTag: true
